# Shows the most commmon methods for strings based on the ruby documentation.
def show_methods
  puts "String methods:"
  puts "  .class: #{'hello'.class}"
  puts "  .length: #{'hello'.length}"
  puts "  .upcase: #{'hello'.upcase}"
  puts "  .downcase: #{'hello'.downcase}"
  puts "  .capitalize: #{'hello'.capitalize}"
  puts "  .swapcase: #{'hello'.swapcase}"
  puts "  .reverse: #{'hello'.reverse}"
  puts "  .concat: #{'hello'.concat(' world')}"
  puts "  .include?: #{'hello'.include?('ello')}"
  puts "  .start_with?: #{'hello'.start_with?('hell')}"
  puts "  .end_with?: #{'hello'.end_with?('o')}"
  puts "  .scan: #{'hello'.scan(/[a-z]/)}"
  puts "  .gsub: #{'hello'.gsub(/[a-z]/, '*')}"
  puts "  .gsub!: #{'hello'.gsub!(/[a-z]/, '*')}"
  puts "  .sub: #{'hello'.sub(/[a-z]/, '*')}"
  puts "  .sub!: #{'hello'.sub!(/[a-z]/, '*')}"
  puts "  .match: #{'hello'.match(/[a-z]/)}"
  puts "  .scan: #{'hello'.scan(/[a-z]/)}"
  puts "  .split: #{'hello'.split(/[a-z]/)}"
  puts "  .chomp: #{'hello'.chomp}"
  puts "  .chomp!: #{'hello'.chomp!}"
  puts "  .strip: #{'hello'.strip}"
  puts "  .strip!: #{'hello'.strip!}"
  puts "  .lstrip: #{'hello'.lstrip}"
  puts "  .lstrip!: #{'hello'.lstrip!}"
  puts "  .rstrip: #{'hello'.rstrip}"
  puts "  .rstrip!: #{'hello'.rstrip!}"
  puts "  .squeeze: #{'hello'.squeeze}"
  puts "  .squeeze!: #{'hello'.squeeze!}"
end